CREATE TABLE IF NOT EXISTS `sys_cabinet_item` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `parent_id` varchar(32) DEFAULT NULL COMMENT '父节点ID',
  `scope` varchar(16) NOT NULL COMMENT '文件柜范围(private/public)',
  `owner_key` varchar(64) NOT NULL COMMENT '归属标识，私柜为用户名，公柜固定PUBLIC',
  `item_type` varchar(16) NOT NULL COMMENT '节点类型(folder/file)',
  `name` varchar(120) NOT NULL COMMENT '名称',
  `ext` varchar(32) DEFAULT NULL COMMENT '扩展名',
  `file_path` varchar(500) DEFAULT NULL COMMENT '文件路径',
  `size_bytes` bigint DEFAULT NULL COMMENT '文件大小(字节)',
  `sort_no` int DEFAULT 10 COMMENT '排序号',
  `icon_key` varchar(64) DEFAULT NULL COMMENT '内置图标key',
  `custom_icon_path` varchar(500) DEFAULT NULL COMMENT '自定义图标路径',
  `has_child` char(1) DEFAULT '0' COMMENT '是否有子节点(0/1)',
  `tenant_id` int DEFAULT 0 COMMENT '租户ID',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_cabinet_parent` (`tenant_id`, `scope`, `owner_key`, `parent_id`),
  KEY `idx_cabinet_file_path` (`file_path`(191)),
  KEY `idx_cabinet_custom_icon_path` (`custom_icon_path`(191)),
  UNIQUE KEY `uk_cabinet_sibling_name` (`tenant_id`, `scope`, `owner_key`, `parent_id`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件柜项目表';
